### ISSUE TITLE
Php version

### ISSUE THREAD

**Issue by sdmg15** [NARKOZ/hacker-scripts#114]
Hi i want you to explain well the script php 
In order to tell me how i can use it or test it 
Thanks

**Comment by antonk52** [comment]
+1

**Comment by sonkengmaldini15** [comment]
??? what does it means .?

**Comment by Michael-Brooks** [comment]
You need to have composer set up, if you don't know what that is then a quick google will sort it for you. You will need to run "composer install" which will install the dependencies within the composer.json file and downloads them into a vendor folder.

For the environment variables, just create a file called ".env" then add the parameters for variables you need to use.
