### ISSUE TITLE
Java fucking coffee implementation does not follow class naming conventions

### ISSUE THREAD

**Issue by Sponges** [NARKOZ/hacker-scripts#122]
https://github.com/NARKOZ/hacker-scripts/blob/master/java/fucking_coffee.java

Class name should be FuckingCoffee

**Comment by cybernet** [comment]
looking a that file in 2 years wouldn't be the same as today, so the correct link to the file is
https://github.com/NARKOZ/hacker-scripts/blob/01f35717c7b3e3c3ff47e206b3420609c1c41270/java/fucking_coffee.java

:)

**Comment by NARKOZ** [comment]
Pull requests are welcome.
