### ISSUE TITLE
[:|||||||||||||||||||||||||:]

### ISSUE THREAD

**Issue by exbarboss** [NARKOZ/hacker-scripts#147]
[:|||||||||||||||||||||||||:]
[:/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/:]
[:|||||||||||||||||||||||||:]
[:/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/:]
[:|||||||||||||||||||||||||:]

**Comment by AnCh7** [comment]
@exbarboss Is this a bayan ?

**Comment by exbarboss** [comment]
@AnCh7 absolutely!

**Comment by Hamza-Kouki** [comment]
?
