### ISSUE TITLE
Use a better license

### ISSUE THREAD

**Issue by ioistired** [NARKOZ/hacker-scripts#160]
MIT perhaps, or if you really want people to just "do what the fuck they want to" use CC0.

**Comment by pahakalle** [comment]
https://en.wikipedia.org/wiki/WTFPL

**Comment by pahakalle** [comment]
What's wrong with the one used?

**Comment by ThePreviousOne** [comment]
The WTFPL isnt a real license. It was created in response to the GPLv3 by some BSD guy.
Licenses need to be able to cross language barriers and still be understood, the product being licensed is irrelevant.

**Comment by wumpus** [comment]
IBM's software licensing team accepts the WTFPL, I don't see any reason to change it.

**Comment by ioistired** [comment]
Yikes, sorry about this. I originally opened this issue because WTFPL is invalid in some jurisdictions due to the profanity alone. It also doesn't disclaim warranties like most licenses do. I can see this was just past me being rude though. Sorry for the trouble.

**Comment by mmahmoudian** [comment]
Just adding to the discussion:

WTFPL is approved by FSF: https://directory.fsf.org/wiki/License:WTFPL

The following is the verbatim of the [FSF comment about WTFPL](https://www.gnu.org/licenses/license-list.html#WTFPL):
> This is a lax permissive non-copyleft free software license, compatible with the GNU GPL.
> 
> We do not recommend this license. If you want a lax permissive license for a small program, we recommend the X11 license. A larger program usually ought to be copyleft; but if you are set on using a lax permissive license for one, we recommend the Apache 2.0 license since it protects users from patent treachery.

Therefore imho it is a very valid license for this repo.

**Comment by ThePreviousOne** [comment]
@mmahmoudian ok but this is still a good reason not to http://cubicspot.blogspot.com/2017/04/wtfpl-is-harmful-to-software-developers.html
I originally got my information from a LibrePlanet Talk I attended years back...I think. I dont really care anymore

**Comment by ThePreviousOne** [comment]
and this https://forum.minetest.net/viewtopic.php?t=15354 on why licencing is important in general

PS
I don't actually care anymore I was just got bored at the time and went on an ANTI-WTFPL rampage

**Comment by mmahmoudian** [comment]
@ThePreviousOne Thanks for the links. They were nice reads. After reading them, the main point that comes to mind is that WTFPL might not be suitable to softwares and brands, but for scripts such as the one this repo is offering, imho there is no need for a thorough license and warranty clause and etc. Most of these scripts are few lines and can be written in any language out there. The value of such script imo is in the ingenuity of the ideas for life automation 😅

Regardless, I highly suggest to others to go through those links, they have some valid points imo.

**Comment by ThePreviousOne** [comment]
@mmahmoudian on that I can agree...now. Before I was just kind of blindly going around making the same blanket statment everywhere
