### ISSUE TITLE
Actually fake

### ISSUE THREAD

**Issue by n158** [NARKOZ/hacker-scripts#168]
This is not actual scripts leaved by genius engineer. Thought this is is actual legacy repository, but actually just a fake.

**Comment by ninetwofour** [comment]
If you actually read the README, you'd see that this is _"Based on a true story"_

[Seen here](https://www.jitbit.com/alexblog/249-now-thats-what-i-call-a-hacker/)

**Comment by VPenkov** [comment]
This is 100% real even if it's 100% fake. Don't let the truth get into the way of a good story.

**Comment by kiri605** [comment]
Oh, my god, this is boring
