### ISSUE TITLE
$HOME/bin/{fucking_coffee,kumar_asshole} missing

### ISSUE THREAD

**Issue by terrywang** [NARKOZ/hacker-scripts#27]
Thanks for the blog post and code ;-D

Really entertained by the story and of course the guy.

Looks like we've already had `kumar-asshole.sh` and `fucking_coffee` implemented in Python and Ruby (hopefully more to come, so many polyglot fans), however, the original shell scripts which are supposed to be in `$HOME/bin` are missing, it'll be great if they can be added.

Thanks again for entertaining the crowd ;-D

**Comment by mablae** [comment]
:+1:

**Comment by FreekingDean** [comment]
All the .sh scripts are the ones your looking for. You can either write an installer for it, or add the directory to your path. What exactly are you looking for?

**Comment by NARKOZ** [comment]
You need to put `{fucking_coffee,kumar_asshole}` to your bin and drop extension from filename. 

Example for Ruby scripts:

```sh
cp fucking_coffee.rb ~/bin/fucking_coffee
cp kumar_asshole.rb ~/bin/kumar_asshole
```

It's up to you.

**Comment by terrywang** [comment]
@NARKOZ Thanks for getting back, I didn't realize {fucking_coffee,kumar_asshole}.rb were the ones, my bad. I thought they were Ruby implementation LoL
