### ISSUE TITLE
kumar script doesn't actually restore the database, right?

### ISSUE THREAD

**Issue by kris-luminar** [NARKOZ/hacker-scripts#33]
I see this comment, but the line below only sets the email subject line.
https://github.com/NARKOZ/hacker-scripts/blob/master/kumar_asshole.rb#L17

**Comment by anantzoid** [comment]
Exactly. I think the kumar story is fake.

**Comment by benmodo** [comment]
I think the comment is supposed to mean that they removed the part of the script that restores the database.

**Comment by anantzoid** [comment]
They could have just removed the credentials/config and keep the remaining code.

**Comment by arsham-f** [comment]
This is a terrible idea anyway.

```
From Kumar:

Thanks for the help yesterday. Sorry to hear about your hangover.
```

*DB rolls back*

I think some natural language processing and analysis would make this more useful.
