### ISSUE TITLE
Need fucking coffee implementation in coffeescript

### ISSUE THREAD

**Issue by kirillseva** [NARKOZ/hacker-scripts#4]

**Comment by hignatious** [comment]
https://www.youtube.com/watch?v=8X_Ot0k4XJc

**Comment by jazzyjester** [comment]
right... where is the gibberish binary code ?!

**Comment by mikeminneman** [comment]
+1

**Comment by manblood** [comment]
it uses telnet to login to coffee machine and code "sys brew" and "sys pour" it seems. 
and database restore code is missing in kumar code... i guess.

**Comment by NARKOZ** [comment]
95a25f20ea8a86e5315c7ce20336b83f8c56814a
