### ISSUE TITLE
Does it scale ?

### ISSUE THREAD

**Issue by azimgd** [NARKOZ/hacker-scripts#43]

**Comment by abdulhannanali** [comment]
hahaha NO!

**Comment by assaad** [comment]
hahahha

**Comment by brennan-macaig** [comment]
This feels like the programming equivalent to "will it blend?"

**Comment by Murilirum** [comment]
![Yes it Scales](https://david-smith.org/resources/coffee-scale.jpg)

**Comment by LijieSong** [comment]
how much?

**Comment by Murilirum** [comment]
30 scale, give or take 1 starbuck

**Comment by LijieSong** [comment]
it's too ........ i don't have things to take it.
