### ISSUE TITLE
No cup exception, cup overflow [security issue]

### ISSUE THREAD

**Issue by ad-m** [NARKOZ/hacker-scripts#9]
Hello,

In story we have 2 sleeps "waits exactly 17 seconds" and " waits another 24 (!) seconds", but the code waits only:
```ruby
sleep 64
```
I think this can be very dangerous to users, due:
* no time to put a cup,
* overflow a cup.

Greetings,

**Comment by jimthenerd** [comment]
````
throw new CoffeeOverFlowException(); 
````

Problem solved!

**Comment by FreekingDean** [comment]
`raise 'CofeeOverFlowExecption'`

**Comment by z3ntu** [comment]
@FreekingDean * `raise 'CoffeeOverFlowException'`

**Comment by FreekingDean** [comment]
@z3ntu no more GH issue responses without spellcheck

**Comment by gdNireus** [comment]
OH ! That's funny

**Comment by NARKOZ** [comment]
cdaf2b0dcdcbc8d8890b499a96d95d21fdd5185d
